# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go PR Check
permissions:
  contents: read

on:
  push:
    branches: 
    - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Go Build and Test
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '>=1.23.0'

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v

    - name: Vet
      run: go vet -v
